export type QuestionLocale = 'es' | 'en';
export type QuestionDestination = 'punta-cana' | 'bayahibe' | 'general';
export type QuestionCategory = 'prices' | 'pickup' | 'safety' | 'route' | 'preparation' | 'planning';

type QuestionSeed = {
  category: QuestionCategory;
  destination: QuestionDestination;
  es: { question: string; answer: string };
  en: { question: string; answer: string };
};

export type BuggyQuestion = QuestionSeed & {
  id: string;
  es: QuestionSeed['es'] & { slug: string };
  en: QuestionSeed['en'] & { slug: string };
};

const s = (
  category: QuestionCategory,
  destination: QuestionDestination,
  esQuestion: string,
  enQuestion: string,
  esAnswer: string,
  enAnswer: string,
): QuestionSeed => ({
  category,
  destination,
  es: { question: esQuestion, answer: esAnswer },
  en: { question: enQuestion, answer: enAnswer },
});

const seeds: QuestionSeed[] = [
  s('prices', 'general', '¿El precio del buggy es por persona o por vehículo?', 'Is the buggy price per person or per vehicle?', 'Los precios publicados son por vehículo según la modalidad individual, doble o familiar. La ficha indica cuántas personas caben y el total se calcula antes de pagar.', 'Published prices are per vehicle for the single, double or family option. Each page shows its capacity and calculates the total before payment.'),
  s('prices', 'punta-cana', '¿Cuánto cuesta un buggy individual en Punta Cana?', 'How much is a single buggy in Punta Cana?', 'El buggy individual en Punta Cana se publica desde US$40 por vehículo para una persona, con recogida coordinada en las zonas principales.', 'The Punta Cana single buggy is listed from US$40 per vehicle for one traveler, with coordinated pickup in the main zones.'),
  s('prices', 'punta-cana', '¿Cuánto cuesta un buggy doble en Punta Cana?', 'How much is a double buggy in Punta Cana?', 'El buggy doble se publica desde US$75 por vehículo para piloto y copiloto. Es la modalidad más elegida por parejas y amigos.', 'The double buggy is listed from US$75 per vehicle for a driver and passenger. It is the most popular option for couples and friends.'),
  s('prices', 'punta-cana', '¿Cuánto cuesta un buggy familiar de cuatro plazas?', 'How much is a four-seat family buggy?', 'El buggy familiar de hasta cuatro plazas se publica desde US$140 por vehículo. El precio cubre el vehículo completo, no una tarifa individual por cada pasajero.', 'The family buggy for up to four travelers is listed from US$140 per vehicle. The price covers the full vehicle rather than a separate rate per passenger.'),
  s('prices', 'bayahibe', '¿Cuánto cuesta un buggy individual en Bayahibe?', 'How much is a single buggy in Bayahibe?', 'El buggy individual de Bayahibe y La Romana se publica desde US$75 por vehículo. La recogida o punto de encuentro se coordina antes del tour.', 'The Bayahibe and La Romana single buggy is listed from US$75 per vehicle. Pickup or the meeting point is coordinated before the tour.'),
  s('prices', 'bayahibe', '¿Cuánto cuesta un buggy doble en Bayahibe?', 'How much is a double buggy in Bayahibe?', 'El buggy doble de Bayahibe se publica desde US$145 por vehículo para dos personas. El formulario muestra el total antes de abrir el pago seguro.', 'The Bayahibe double buggy is listed from US$145 per vehicle for two travelers. The form shows the total before secure payment opens.'),
  s('prices', 'bayahibe', '¿Cuánto cuesta un buggy familiar en Bayahibe?', 'How much is a family buggy in Bayahibe?', 'La modalidad familiar de Bayahibe, con capacidad de hasta cuatro personas, se publica desde US$290 por vehículo.', 'The Bayahibe family option, with capacity for up to four travelers, is listed from US$290 per vehicle.'),
  s('prices', 'general', '¿La recogida en el hotel está incluida en el precio?', 'Is hotel pickup included in the price?', 'La recogida coordinada está incluida en las zonas principales indicadas. Cap Cana y Uvero Alto pueden generar un suplemento visible al seleccionar la zona.', 'Coordinated pickup is included in the listed main zones. Cap Cana and Uvero Alto may add a clearly displayed zone surcharge.'),
  s('prices', 'general', '¿Hay cargos ocultos al reservar el buggy?', 'Are there hidden fees when booking the buggy?', 'El formulario muestra vehículo, cantidad necesaria y suplemento de zona antes del pago. Una ubicación fuera de las zonas publicadas debe confirmarse por WhatsApp.', 'The form shows the vehicle, quantity needed and any zone surcharge before payment. Locations outside the listed zones must be confirmed by WhatsApp.'),
  s('prices', 'punta-cana', '¿Cuánto cuesta la recogida desde Cap Cana o Uvero Alto?', 'How much is pickup from Cap Cana or Uvero Alto?', 'El calculador publica un suplemento de US$10 para Cap Cana y US$15 para Uvero Alto. La ruta y hora exacta se confirman después de reservar.', 'The calculator lists a US$10 surcharge for Cap Cana and US$15 for Uvero Alto. The exact route and pickup time are confirmed after booking.'),
  s('prices', 'general', '¿Puedo pagar el tour en buggy con tarjeta?', 'Can I pay for the buggy tour by card?', 'Sí. El checkout permite abrir un pago seguro y PayPal puede mostrar pago directo con tarjeta según el país y el navegador del cliente.', 'Yes. Checkout opens secure payment, and PayPal may offer direct card payment depending on the traveler’s country and browser.'),
  s('prices', 'general', '¿Puedo pagar el buggy con PayPal?', 'Can I pay for the buggy with PayPal?', 'Sí. PayPal está integrado en la reserva y el total se presenta en dólares estadounidenses antes de autorizar el pago.', 'Yes. PayPal is integrated into booking, and the total is displayed in US dollars before payment is authorized.'),
  s('prices', 'general', '¿Es seguro pagar el buggy por internet?', 'Is it safe to pay for the buggy online?', 'El sitio no procesa directamente los datos de la tarjeta: el pago se completa mediante PayPal y sus métodos disponibles. Después se confirma la recogida por WhatsApp o correo.', 'The website does not process card details directly: payment is completed through PayPal and its available methods. Pickup is then confirmed by WhatsApp or email.'),
  s('prices', 'general', '¿Puedo reservar el buggy por WhatsApp antes de pagar?', 'Can I reserve the buggy by WhatsApp before paying?', 'Puedes abrir WhatsApp desde cualquier página para consultar disponibilidad y condiciones. Para asegurar la plaza, el equipo indicará el proceso de confirmación aplicable.', 'You can open WhatsApp from any page to ask about availability and conditions. The team will explain the applicable confirmation process to secure the spot.'),
  s('prices', 'general', '¿El precio cambia si reservo el mismo día?', 'Does the price change for a same-day booking?', 'La tarifa visible es la referencia web, pero una reserva para el mismo día depende de disponibilidad operativa. Confirma plaza y horario por WhatsApp antes de pagar.', 'The displayed rate is the web reference, but same-day bookings depend on operating availability. Confirm the spot and schedule by WhatsApp before paying.'),

  s('pickup', 'punta-cana', '¿Qué hoteles tienen recogida para el buggy en Punta Cana?', 'Which Punta Cana hotels have buggy pickup?', 'Hay páginas de recogida para hoteles populares de Bávaro, Arena Gorda, Cabeza de Toro, Macao, Cap Cana y Uvero Alto. Busca tu hotel y confirma el punto autorizado.', 'Pickup pages cover popular hotels in Bavaro, Arena Gorda, Cabeza de Toro, Macao, Cap Cana and Uvero Alto. Find your hotel and confirm its authorized point.'),
  s('pickup', 'punta-cana', '¿Hay recogida desde hoteles de Bávaro?', 'Is pickup available from Bavaro hotels?', 'Sí, los hoteles principales de Bávaro forman parte de las zonas habituales de recogida coordinada. La hora depende de la ruta del día y del hotel seleccionado.', 'Yes. Major Bavaro hotels are within the usual coordinated pickup zones. Timing depends on the day’s route and selected hotel.'),
  s('pickup', 'punta-cana', '¿Hay recogida desde Uvero Alto?', 'Is pickup available from Uvero Alto?', 'Uvero Alto aparece como zona disponible con un suplemento publicado de US$15. El equipo confirma el punto y la hora exacta después de reservar.', 'Uvero Alto is available with a listed US$15 surcharge. The team confirms the exact point and time after booking.'),
  s('pickup', 'punta-cana', '¿Hay recogida desde Cap Cana?', 'Is pickup available from Cap Cana?', 'Cap Cana aparece como zona disponible con un suplemento publicado de US$10. Debes indicar el hotel o alojamiento exacto en el formulario.', 'Cap Cana is available with a listed US$10 surcharge. Enter the exact hotel or accommodation in the booking form.'),
  s('pickup', 'punta-cana', '¿Hay recogida desde Cabeza de Toro?', 'Is pickup available from Cabeza de Toro?', 'Sí, Cabeza de Toro figura entre las zonas principales sin suplemento de zona en el calculador. El lobby o punto de tours se confirma por mensaje.', 'Yes. Cabeza de Toro is listed among the main zones without a zone surcharge in the calculator. The lobby or tours point is confirmed by message.'),
  s('pickup', 'punta-cana', '¿Hay recogida desde Macao?', 'Is pickup available from Macao?', 'Macao está incluido entre los puntos de recogida publicados. La coordinación exacta depende del alojamiento y del acceso autorizado para excursiones.', 'Macao is included among the published pickup points. Exact coordination depends on the accommodation and its authorized excursion access.'),
  s('pickup', 'general', '¿Pueden recogerme en un Airbnb o apartamento?', 'Can you pick me up from an Airbnb or apartment?', 'Escribe la dirección o punto de referencia en el formulario. El equipo confirmará si llega hasta el alojamiento o si necesita asignar un punto de encuentro cercano.', 'Enter the address or landmark in the form. The team will confirm whether pickup reaches the accommodation or requires a nearby meeting point.'),
  s('pickup', 'general', '¿Cuándo sabré la hora exacta de recogida?', 'When will I receive the exact pickup time?', 'La hora exacta se confirma por WhatsApp o correo después de revisar fecha, hotel, zona y tanda disponible. No dependas solo de una hora estimada de la web.', 'The exact time is confirmed by WhatsApp or email after reviewing the date, hotel, zone and available departure. Do not rely only on a website estimate.'),
  s('pickup', 'general', '¿La recogida es en el lobby del hotel?', 'Is pickup from the hotel lobby?', 'Puede ser el lobby, el área autorizada de tours o un punto cercano indicado por el hotel. La confirmación final especificará dónde debes esperar.', 'Pickup may be at the lobby, authorized tours area or a nearby point designated by the hotel. Final confirmation tells you exactly where to wait.'),
  s('pickup', 'general', '¿El tour me devuelve al mismo hotel?', 'Does the tour return me to the same hotel?', 'La experiencia incluye transporte de regreso al punto coordinado, salvo que se acuerde expresamente otra logística antes del servicio.', 'The experience includes return transportation to the coordinated point unless different logistics are expressly agreed before the service.'),
  s('pickup', 'punta-cana', '¿Cuánto dura el tour incluyendo el transporte?', 'How long is the tour including transportation?', 'Las modalidades publicadas indican aproximadamente cuatro horas con traslado. El tiempo total puede variar por hotel, tráfico, recogidas y operación del día.', 'Published options indicate approximately four hours with transfer. Total time may vary by hotel, traffic, pickup route and daily operations.'),
  s('pickup', 'punta-cana', '¿Cuánto se tarda del hotel al rancho de buggy?', 'How long is the transfer from the hotel to the buggy ranch?', 'Depende de la zona. Las páginas de hotel muestran estimaciones habituales, pero el tiempo real cambia con tráfico, ruta de recogida y número de paradas.', 'It depends on the zone. Hotel pages show typical estimates, but actual time changes with traffic, pickup routing and the number of stops.'),
  s('pickup', 'punta-cana', '¿Hay recogida para el Hard Rock Hotel Punta Cana?', 'Is pickup available from Hard Rock Hotel Punta Cana?', 'Sí, existe una página específica para coordinar recogida desde Hard Rock. El punto suele ser el área autorizada de excursiones confirmada por el hotel.', 'Yes. There is a dedicated page for coordinating pickup from Hard Rock. The point is normally the hotel-authorized excursion area.'),
  s('pickup', 'punta-cana', '¿Hay recogida desde hoteles RIU de Punta Cana?', 'Is pickup available from RIU hotels in Punta Cana?', 'Varios hoteles RIU tienen páginas específicas de recogida. Selecciona el nombre exacto porque RIU Republica, Palace, Bávaro y Bambu pueden usar rutas diferentes.', 'Several RIU hotels have dedicated pickup pages. Select the exact property because RIU Republica, Palace, Bavaro and Bambu may use different routes.'),
  s('pickup', 'punta-cana', '¿Hay recogida desde Lopesan Costa Bávaro?', 'Is pickup available from Lopesan Costa Bavaro?', 'Sí, Lopesan Costa Bávaro tiene una landing de recogida. La hora y el punto autorizado se confirman con los datos de la reserva.', 'Yes. Lopesan Costa Bavaro has a dedicated pickup landing page. Its time and authorized point are confirmed with the booking details.'),
  s('pickup', 'bayahibe', '¿Hay recogida desde hoteles de Bayahibe?', 'Is pickup available from Bayahibe hotels?', 'Las opciones de Bayahibe incluyen coordinación de recogida o punto de encuentro. Es importante seleccionar Bayahibe/La Romana y escribir el hotel exacto.', 'Bayahibe options include coordinated pickup or a meeting point. Select Bayahibe/La Romana and enter the exact hotel.'),
  s('pickup', 'bayahibe', '¿Hay recogida desde hoteles de La Romana?', 'Is pickup available from La Romana hotels?', 'La recogida en La Romana se confirma según el hotel y la ruta operativa. Añade el alojamiento completo para que el equipo asigne el punto correcto.', 'Pickup in La Romana is confirmed according to the hotel and operating route. Enter the full accommodation name so the team can assign the correct point.'),
  s('pickup', 'bayahibe', '¿Pueden recogerme en el puerto de La Romana?', 'Can you pick me up from La Romana cruise port?', 'La recogida portuaria no debe asumirse como incluida. Envía barco, fecha y horario por WhatsApp para confirmar acceso, margen de regreso y punto de encuentro.', 'Cruise-port pickup should not be assumed to be included. Send the ship, date and schedule by WhatsApp to confirm access, return margin and meeting point.'),
  s('pickup', 'general', '¿La recogida desde el aeropuerto está incluida?', 'Is airport pickup included?', 'El transporte publicado se refiere a la excursión desde hoteles o puntos coordinados, no a un traslado aeroportuario. Consulta una coordinación especial antes de reservar.', 'Published transportation refers to the excursion from hotels or coordinated points, not an airport transfer. Ask about special coordination before booking.'),
  s('pickup', 'general', '¿Puedo solicitar recogida privada?', 'Can I request private pickup?', 'La recogida privada no forma parte de las opciones estándar del formulario. Si necesitas transporte exclusivo, consulta disponibilidad y precio por WhatsApp.', 'Private pickup is not part of the standard form options. If you need exclusive transportation, ask about availability and pricing by WhatsApp.'),

  s('safety', 'general', '¿Cuál es la edad mínima para conducir un buggy?', 'What is the minimum age to drive a buggy?', 'El conductor debe tener al menos 18 años y saber conducir. Debe seguir las instrucciones del guía y las reglas operativas del día.', 'Drivers must be at least 18 and know how to drive. They must follow the guide’s instructions and the day’s operating rules.'),
  s('safety', 'general', '¿Necesito licencia de conducir para manejar el buggy?', 'Do I need a driver’s license to drive the buggy?', 'El requisito publicado es ser mayor de 18 años y saber conducir. Lleva una licencia vigente y confirma por WhatsApp si será solicitada para tu modalidad.', 'The published requirement is to be 18+ and know how to drive. Bring a valid license and confirm by WhatsApp whether it is required for your option.'),
  s('safety', 'general', '¿Necesito experiencia previa manejando buggy?', 'Do I need previous buggy driving experience?', 'No se publica experiencia off-road obligatoria, pero debes saber conducir. Antes de salir recibes instrucciones de seguridad y debes respetar al guía.', 'No previous off-road experience is listed as mandatory, but you must know how to drive. You receive safety instructions before departure and must follow the guide.'),
  s('safety', 'general', '¿Pueden ir niños en el tour de buggy?', 'Can children join the buggy tour?', 'Sí, pueden viajar como acompañantes cuando cumplen la edad mínima publicada de tres años y la modalidad tiene una plaza segura disponible.', 'Yes. Children may ride as passengers when they meet the published minimum age of three and the selected vehicle has a safe available seat.'),
  s('safety', 'general', '¿Cuál es la edad mínima para un niño acompañante?', 'What is the minimum age for a child passenger?', 'La edad mínima publicada para niños acompañantes es de tres años. Comparte la edad exacta antes de reservar para validar la modalidad adecuada.', 'The published minimum age for child passengers is three. Share the exact age before booking to validate the appropriate option.'),
  s('safety', 'general', '¿Puede hacer el tour una mujer embarazada?', 'Can a pregnant traveler take the buggy tour?', 'No. El tour no se recomienda para mujeres embarazadas por los golpes, charcos y terreno irregular de la ruta off-road.', 'No. The tour is not recommended during pregnancy because of bumps, puddles and uneven off-road terrain.'),
  s('safety', 'general', '¿Puedo ir si tengo problemas de espalda o cuello?', 'Can I join with back or neck problems?', 'No se recomienda para personas con problemas severos de espalda. Si existe una condición de cuello, cirugía o lesión, consulta al médico y al operador antes de reservar.', 'It is not recommended for travelers with severe back problems. For neck conditions, surgery or injury, consult both a doctor and the operator before booking.'),
  s('safety', 'general', '¿El tour incluye casco y equipo de seguridad?', 'Does the tour include a helmet and safety equipment?', 'Sí. Las inclusiones publicadas contemplan casco, equipo de seguridad e instrucciones antes de comenzar la conducción.', 'Yes. Published inclusions cover a helmet, safety equipment and instructions before driving begins.'),
  s('safety', 'general', '¿Hay un guía durante toda la ruta?', 'Is there a guide throughout the route?', 'Sí. La experiencia se realiza con guía y asistencia durante el recorrido. Debes mantenerte dentro del grupo y seguir sus indicaciones.', 'Yes. The experience includes a guide and route support. Stay with the group and follow all instructions.'),
  s('safety', 'general', '¿Es seguro el buggy para principiantes?', 'Is the buggy tour safe for beginners?', 'Puede ser apto para principiantes que sepan conducir y sigan la charla de seguridad. El terreno es real, irregular y con lodo, no una pista pavimentada.', 'It can suit beginners who know how to drive and follow the safety briefing. The terrain is genuinely uneven and muddy rather than paved.'),
  s('safety', 'general', '¿Podemos cambiar de conductor durante el tour?', 'Can we switch drivers during the tour?', 'En un buggy doble o familiar puede ser posible únicamente cuando el guía autorice el cambio en un punto seguro y el nuevo conductor cumpla los requisitos.', 'In a double or family buggy, switching may be possible only when the guide authorizes it at a safe point and the new driver meets all requirements.'),
  s('safety', 'general', '¿Puedo conducir después de consumir alcohol?', 'Can I drive after drinking alcohol?', 'No debes conducir bajo los efectos del alcohol o sustancias. La degustación local es controlada y siempre prevalecen las instrucciones de seguridad.', 'Do not drive under the influence of alcohol or substances. Local tasting is controlled, and safety instructions always take priority.'),
  s('safety', 'general', '¿El tour es accesible para personas con movilidad reducida?', 'Is the tour accessible for travelers with limited mobility?', 'El terreno irregular, el acceso al buggy y las paradas pueden crear barreras. Describe la necesidad concreta por WhatsApp antes de reservar para recibir una evaluación honesta.', 'Uneven terrain, buggy access and stops may create barriers. Describe the specific need by WhatsApp before booking for an honest assessment.'),
  s('safety', 'general', '¿Puedo hacer el tour si tengo una condición médica?', 'Can I take the tour with a medical condition?', 'Depende de la condición y de la tolerancia a golpes, calor y terreno irregular. Consulta a tu médico y comparte las limitaciones con el equipo antes de pagar.', 'It depends on the condition and tolerance for bumps, heat and uneven terrain. Consult your doctor and share limitations with the team before paying.'),
  s('safety', 'general', '¿Recibimos instrucciones antes de manejar?', 'Do we receive instructions before driving?', 'Sí. El tour incluye una explicación de seguridad, asignación del vehículo y reglas para mantener distancia y seguir al guía.', 'Yes. The tour includes a safety explanation, vehicle assignment and rules for keeping distance and following the guide.'),

  s('route', 'punta-cana', '¿El tour en buggy visita Playa Macao?', 'Does the buggy tour visit Macao Beach?', 'Las rutas de Punta Cana publicadas incluyen una visita a Playa Macao, sujeta a las condiciones operativas, clima y orden de paradas del día.', 'Published Punta Cana routes include a Macao Beach visit, subject to operating conditions, weather and the day’s stop order.'),
  s('route', 'punta-cana', '¿El buggy llega hasta un cenote?', 'Does the buggy tour visit a cenote?', 'Sí, la ruta de Punta Cana incluye una parada en cenote. El tiempo de baño y acceso puede ajustarse por seguridad u operación.', 'Yes. The Punta Cana route includes a cenote stop. Swim time and access may be adjusted for safety or operating reasons.'),
  s('route', 'punta-cana', '¿Se puede nadar en el cenote?', 'Can you swim in the cenote?', 'La parada está planteada para disfrutar el cenote y normalmente permite baño cuando las condiciones lo permiten. Sigue siempre las instrucciones del guía.', 'The stop is designed for enjoying the cenote and normally allows swimming when conditions permit. Always follow the guide’s instructions.'),
  s('route', 'punta-cana', '¿El tour visita un rancho dominicano?', 'Does the tour visit a Dominican ranch?', 'Sí. La ruta publicada incluye una parada cultural en un rancho dominicano como parte de la experiencia de Macao.', 'Yes. The published route includes a cultural stop at a Dominican ranch as part of the Macao experience.'),
  s('route', 'punta-cana', '¿Hay degustación de café, cacao y mamajuana?', 'Is there coffee, cacao and mamajuana tasting?', 'Sí. La degustación de café, cacao y mamajuana figura entre las inclusiones del tour de Punta Cana.', 'Yes. Coffee, cacao and mamajuana tasting is listed among the Punta Cana tour inclusions.'),
  s('route', 'punta-cana', '¿Hay lodo de verdad en la ruta?', 'Is there real mud on the route?', 'Sí, es una ruta off-road con caminos rurales, polvo, charcos y lodo. La cantidad cambia con el clima y las condiciones del terreno.', 'Yes. This is an off-road route with rural roads, dust, puddles and mud. The amount varies with weather and trail conditions.'),
  s('route', 'punta-cana', '¿Cuánto tiempo se conduce el buggy?', 'How much actual buggy driving time is included?', 'La experiencia completa ronda cuatro horas con traslado y varias paradas. El tiempo exacto al volante varía por tráfico, grupo, ruta y operación.', 'The complete experience is around four hours with transfers and several stops. Exact time behind the wheel varies by traffic, group, route and operations.'),
  s('route', 'general', '¿Qué diferencia hay entre buggy individual, doble y familiar?', 'What is the difference between single, double and family buggies?', 'El individual es para una persona, el doble para piloto y copiloto, y el familiar permite hasta cuatro pasajeros. El precio se calcula por vehículo.', 'The single is for one traveler, the double for driver and passenger, and the family option holds up to four. Pricing is calculated per vehicle.'),
  s('route', 'general', '¿Qué incluye el buggy individual?', 'What is included with the single buggy?', 'Incluye el vehículo para un conductor, transporte coordinado, casco, guía y las paradas correspondientes a la ruta elegida.', 'It includes the vehicle for one driver, coordinated transportation, helmet, guide and the stops associated with the selected route.'),
  s('route', 'general', '¿Qué incluye el buggy doble?', 'What is included with the double buggy?', 'Incluye un vehículo para dos personas, transporte coordinado, equipo de seguridad, guía y las paradas publicadas para el destino.', 'It includes one vehicle for two travelers, coordinated transportation, safety equipment, guide and the published destination stops.'),
  s('route', 'general', '¿Qué incluye el buggy familiar?', 'What is included with the family buggy?', 'Incluye un vehículo de hasta cuatro plazas, transporte coordinado, equipo de seguridad, guía y asistencia durante la ruta.', 'It includes a vehicle with up to four seats, coordinated transportation, safety equipment, guide and support during the route.'),
  s('route', 'bayahibe', '¿Cómo es la ruta de buggy en Bayahibe?', 'What is the Bayahibe buggy route like?', 'La experiencia de Bayahibe combina caminos rurales, tramos off-road, vegetación y ambiente local de La Romana. Las paradas exactas se confirman según la operación.', 'The Bayahibe experience combines rural roads, off-road sections, vegetation and La Romana’s local setting. Exact stops are confirmed according to operations.'),
  s('route', 'bayahibe', '¿El buggy de Bayahibe visita Río Chavón?', 'Does the Bayahibe buggy tour visit the Chavon River?', 'Río Chavón aparece como referencia de la zona, pero no debes asumir una parada fija. Confirma el recorrido exacto disponible para tu fecha antes de pagar.', 'The Chavon River is a regional route reference, but a fixed stop should not be assumed. Confirm the exact itinerary available for your date before paying.'),
  s('route', 'general', '¿Buggy y ATV son la misma excursión?', 'Are buggy and ATV tours the same?', 'No necesariamente. Un buggy tiene estructura, asientos y volante; un ATV suele conducirse a horcajadas. Reserva la modalidad que aparezca claramente en la ficha.', 'Not necessarily. A buggy has a frame, seats and steering wheel, while an ATV is usually straddled. Book only the vehicle type clearly shown on the product page.'),
  s('route', 'general', '¿El tour es privado o se hace con un grupo?', 'Is the tour private or operated with a group?', 'La salida estándar es guiada y puede compartir horario y ruta con otros viajeros. Un servicio privado solo debe considerarse confirmado si el equipo lo acepta expresamente.', 'The standard departure is guided and may share its schedule and route with other travelers. A private service is confirmed only when expressly accepted by the team.'),
  s('route', 'general', '¿En qué idiomas habla el guía?', 'Which languages does the guide speak?', 'Se publica guía multilingüe y el formulario permite indicar el idioma. Confirma la disponibilidad del idioma preferido para la tanda seleccionada.', 'A multilingual guide is listed, and the form lets you state your language. Confirm availability for the selected departure.'),
  s('route', 'general', '¿Las fotos del tour están incluidas?', 'Are tour photos included?', 'Las fotos profesionales no forman parte del precio publicado. Puedes llevar tu teléfono protegido y consultar en ruta si existe un servicio local de fotografías.', 'Professional photos are not part of the published price. You may bring a protected phone and ask on site whether a local photo service is available.'),
  s('route', 'general', '¿Los souvenirs están incluidos?', 'Are souvenirs included?', 'No. Los recuerdos o productos que decidas comprar durante las paradas son gastos personales opcionales.', 'No. Souvenirs or products purchased during stops are optional personal expenses.'),
  s('route', 'general', '¿La comida está incluida en el tour?', 'Is food included with the tour?', 'No se publica una comida completa como inclusión. La experiencia contempla degustación en las rutas donde se especifica, pero lleva efectivo si deseas comprar algo adicional.', 'A full meal is not listed as included. Routes may include the stated tasting, but bring cash if you want to buy anything extra.'),
  s('route', 'general', '¿Las bebidas están incluidas?', 'Are drinks included?', 'No se publican bebidas adicionales como parte del precio. Lleva agua y consulta al equipo sobre disponibilidad durante las paradas.', 'Extra drinks are not listed as part of the price. Bring water and ask the team what is available during stops.'),

  s('preparation', 'general', '¿Qué ropa debo usar para el tour en buggy?', 'What should I wear for a buggy tour?', 'Usa ropa cómoda y vieja que pueda mancharse con lodo, polvo y agua. Evita prendas delicadas o difíciles de asegurar durante la conducción.', 'Wear comfortable old clothes that can get muddy, dusty and wet. Avoid delicate or loose items that are difficult to secure while driving.'),
  s('preparation', 'general', '¿Qué zapatos son mejores para el buggy?', 'What shoes are best for a buggy tour?', 'Usa calzado cerrado o sandalias deportivas bien sujetas que puedan mojarse y ensuciarse. Evita calzado suelto al conducir.', 'Wear closed shoes or secure sports sandals that can get wet and dirty. Avoid loose footwear while driving.'),
  s('preparation', 'punta-cana', '¿Debo llevar traje de baño?', 'Should I bring a swimsuit?', 'Sí. La ruta de Punta Cana contempla cenote y playa, por lo que conviene llevar el traje puesto o bajo la ropa.', 'Yes. The Punta Cana route includes a cenote and beach, so wear a swimsuit or bring one under your clothes.'),
  s('preparation', 'punta-cana', '¿Debo llevar una toalla?', 'Should I bring a towel?', 'Sí, lleva una toalla para las paradas de agua. No aparece como artículo proporcionado dentro de las inclusiones.', 'Yes. Bring a towel for water stops. It is not listed as an item provided with the tour.'),
  s('preparation', 'general', '¿Necesito protector solar?', 'Do I need sunscreen?', 'Sí, utiliza protector solar biodegradable y aplícalo antes de salir. También conviene llevar protección adicional para las paradas al aire libre.', 'Yes. Use biodegradable sunscreen before departure and bring additional sun protection for outdoor stops.'),
  s('preparation', 'general', '¿Conviene llevar gafas para el polvo?', 'Should I bring eye protection for dust?', 'Sí. Gafas de sol cerradas o protección para polvo ayudan en caminos secos. Deben quedar bien ajustadas y no limitar la visión.', 'Yes. Close-fitting sunglasses or dust protection help on dry trails. They should fit securely without limiting vision.'),
  s('preparation', 'general', '¿Necesito pañuelo o bandana para el buggy?', 'Do I need a bandana for the buggy?', 'Es recomendable para polvo y lodo, aunque no figura como inclusión garantizada. Puedes llevar la tuya o consultar si se vende en el punto de salida.', 'It is recommended for dust and mud but is not listed as guaranteed equipment. Bring your own or ask whether one is sold at departure.'),
  s('preparation', 'general', '¿Puedo llevar el teléfono o una cámara?', 'Can I bring a phone or camera?', 'Sí, bajo tu responsabilidad. Usa una funda impermeable con correa y evita manipular el dispositivo mientras conduces.', 'Yes, at your own risk. Use a waterproof case with a strap and never handle the device while driving.'),
  s('preparation', 'general', '¿Debo llevar un cambio de ropa?', 'Should I bring a change of clothes?', 'Es muy recomendable porque probablemente terminarás con lodo o agua. Guarda la ropa limpia en una bolsa impermeable.', 'It is strongly recommended because you will likely finish muddy or wet. Keep clean clothing in a waterproof bag.'),
  s('preparation', 'general', '¿Debo llevar efectivo al tour?', 'Should I bring cash on the tour?', 'Es opcional para bebidas, propinas, fotos o souvenirs. Mantén el efectivo protegido del agua y el lodo.', 'Cash is optional for drinks, tips, photos or souvenirs. Keep it protected from water and mud.'),
  s('preparation', 'general', '¿El tour sale cuando llueve?', 'Does the buggy tour operate in the rain?', 'La lluvia puede hacer la ruta más lodosa, pero la decisión depende de seguridad y operación. Espera la confirmación del equipo antes de desplazarte.', 'Rain can make the route muddier, but operation depends on safety and conditions. Wait for the team’s confirmation before traveling to pickup.'),
  s('preparation', 'general', '¿Qué pasa si cancelan el buggy por mal tiempo?', 'What happens if weather cancels the buggy tour?', 'El equipo debe comunicar reprogramación o la solución aplicable según la reserva. Confirma la política concreta antes de pagar, porque no se publica una regla universal.', 'The team should communicate rescheduling or the applicable solution. Confirm the specific policy before paying because no universal rule is published.'),
  s('preparation', 'general', '¿Es mejor reservar por la mañana o por la tarde?', 'Is a morning or afternoon buggy tour better?', 'Depende de tu itinerario, clima y disponibilidad. El formulario permite indicar un turno preferido, pero la hora final se confirma según la operación.', 'It depends on your itinerary, weather and availability. The form lets you request a preferred window, but final timing is operationally confirmed.'),
  s('preparation', 'general', '¿Con cuánto tiempo debo estar listo para la recogida?', 'How early should I be ready for pickup?', 'Sigue la hora indicada en la confirmación y llega al punto con antelación. Si el mensaje no especifica margen, pregunta por WhatsApp el día anterior.', 'Follow the confirmed time and arrive at the point early. If no margin is specified, ask by WhatsApp the day before.'),
  s('preparation', 'general', '¿Dónde guardo mis pertenencias durante el tour?', 'Where can I keep belongings during the tour?', 'Lleva solo lo esencial en una bolsa pequeña e impermeable. La disponibilidad de casilleros no está garantizada y debe consultarse antes de salir.', 'Bring only essentials in a small waterproof bag. Locker availability is not guaranteed and should be confirmed before departure.'),

  s('planning', 'punta-cana', '¿Vale la pena hacer un tour en buggy en Punta Cana?', 'Is a Punta Cana buggy tour worth it?', 'Es una buena opción si buscas aventura corta, lodo, campo dominicano, cenote y Playa Macao. No es ideal si prefieres una actividad limpia o sin terreno irregular.', 'It is a strong choice for a shorter adventure with mud, countryside, cenote and Macao Beach. It is not ideal if you prefer a clean or smooth activity.'),
  s('planning', 'general', '¿Es mejor reservar el buggy en el hotel o directamente?', 'Is it better to book the buggy at the hotel or directly?', 'Reservar directamente permite comparar el precio por vehículo y completar los datos sin comisión del mostrador. Verifica siempre operador, inclusiones y recogida antes de pagar.', 'Booking direct lets you compare per-vehicle pricing and enter details without a hotel-desk commission. Always verify the operator, inclusions and pickup before paying.'),
  s('planning', 'general', '¿Qué diferencia hay entre el buggy de Punta Cana y el de Bayahibe?', 'What is the difference between Punta Cana and Bayahibe buggy tours?', 'Punta Cana se enfoca en Macao, cenote, rancho y playa. Bayahibe/La Romana ofrece una experiencia rural 4x4 cuya ruta exacta se coordina según la operación.', 'Punta Cana focuses on Macao, cenote, ranch and beach. Bayahibe/La Romana offers a rural 4x4 experience whose exact route is coordinated operationally.'),
  s('planning', 'general', '¿Cuál buggy es mejor para una pareja?', 'Which buggy is best for a couple?', 'El buggy doble está diseñado para piloto y copiloto y suele ser la opción más práctica para parejas. El precio es por el vehículo completo.', 'The double buggy is designed for a driver and passenger and is usually the most practical option for couples. Pricing covers the full vehicle.'),
  s('planning', 'general', '¿Cuál buggy es mejor para una familia?', 'Which buggy is best for a family?', 'El buggy familiar permite hasta cuatro personas juntas. Verifica edades, plazas disponibles y que todos puedan realizar una ruta con golpes y lodo.', 'The family buggy keeps up to four travelers together. Verify ages, available seats and that everyone can handle a bumpy, muddy route.'),
  s('planning', 'general', '¿Puedo reservar un buggy si viajo solo?', 'Can I book a buggy as a solo traveler?', 'Sí. La modalidad individual está pensada para una persona que quiere conducir su propio vehículo durante la ruta.', 'Yes. The single option is designed for one traveler who wants to drive their own vehicle during the route.'),
  s('planning', 'general', '¿Aceptan grupos grandes para el tour de buggy?', 'Can large groups book a buggy tour?', 'Sí, el calculador puede estimar varios vehículos según pasajeros y capacidad. Para grupos grandes conviene confirmar disponibilidad conjunta antes del pago.', 'Yes. The calculator can estimate multiple vehicles according to passengers and capacity. Large groups should confirm shared availability before payment.'),
  s('planning', 'general', '¿Cómo elijo entre buggy individual, doble o familiar?', 'How do I choose between single, double and family buggies?', 'Elige según cuántas personas compartirán cada vehículo: una, dos o hasta cuatro. Si el grupo supera la capacidad, el calculador añade los vehículos necesarios.', 'Choose according to how many travelers share each vehicle: one, two or up to four. If the group exceeds capacity, the calculator adds the vehicles needed.'),
  s('planning', 'general', '¿Con cuánta anticipación debo reservar?', 'How far in advance should I book?', 'Reserva cuando tengas fecha y hotel confirmados, especialmente si deseas una tanda concreta o viajas en grupo. Las plazas del mismo día dependen de operación.', 'Book once your date and hotel are confirmed, especially for a preferred departure or group. Same-day space depends on operations.'),
  s('planning', 'bayahibe', '¿Puedo hacer el buggy durante una escala de crucero en La Romana?', 'Can I take the buggy during a La Romana cruise stop?', 'Solo si horarios, transporte y margen de regreso están confirmados por escrito. Envía la hora límite de embarque y no uses una duración aproximada como garantía.', 'Only when timing, transportation and return margin are confirmed in writing. Send the all-aboard time and never treat an approximate duration as a guarantee.'),
  s('planning', 'bayahibe', '¿Puedo combinar buggy en Bayahibe con Isla Saona?', 'Can I combine a Bayahibe buggy tour with Saona Island?', 'Son experiencias separadas y normalmente requieren horarios distintos. Consulta fechas u organización especial sin asumir que ambas caben cómodamente el mismo día.', 'They are separate experiences and normally require different schedules. Ask about dates or special planning rather than assuming both fit comfortably in one day.'),
  s('planning', 'general', '¿El buggy es una buena excursión para la primera visita?', 'Is a buggy tour good for a first visit?', 'Sí, si deseas combinar aventura y paisaje local en medio día. Revisa requisitos, ropa, recogida y destino para evitar expectativas equivocadas.', 'Yes, if you want to combine adventure and local scenery in a half-day experience. Review requirements, clothing, pickup and destination to set the right expectations.'),
  s('planning', 'general', '¿Qué ocurre después de completar la reserva?', 'What happens after completing the booking?', 'El equipo revisa disponibilidad y datos, y confirma por WhatsApp o correo la hora, el punto de recogida y cualquier detalle operativo.', 'The team reviews availability and details, then confirms the time, pickup point and operational information by WhatsApp or email.'),
  s('planning', 'general', '¿Cómo sé que mi reserva de buggy está confirmada?', 'How do I know my buggy booking is confirmed?', 'Debes recibir confirmación con referencia, fecha, modalidad y recogida. Si solo enviaste una consulta, espera la respuesta antes de considerarla una plaza confirmada.', 'You should receive confirmation with a reference, date, option and pickup. If you only sent an inquiry, wait for a response before treating it as confirmed.'),
  s('planning', 'general', '¿Debo elegir Punta Cana o Bayahibe para mi tour?', 'Should I choose Punta Cana or Bayahibe for my buggy tour?', 'Elige el destino donde te alojas: Punta Cana para Macao, cenote y playa; Bayahibe/La Romana para la ruta rural local y una recogida más lógica desde esa zona.', 'Choose where you are staying: Punta Cana for Macao, cenote and beach; Bayahibe/La Romana for its local rural route and more practical pickup from that area.'),
];

function slugify(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export const buggyQuestions: BuggyQuestion[] = seeds.map((seed, index) => ({
  ...seed,
  id: `buggy-question-${String(index + 1).padStart(3, '0')}`,
  es: { ...seed.es, slug: slugify(seed.es.question) },
  en: { ...seed.en, slug: slugify(seed.en.question) },
}));

export const questionCategories: Array<{
  id: QuestionCategory;
  es: string;
  en: string;
}> = [
  { id: 'prices', es: 'Precios y pagos', en: 'Prices and payment' },
  { id: 'pickup', es: 'Recogida y transporte', en: 'Pickup and transportation' },
  { id: 'safety', es: 'Requisitos y seguridad', en: 'Requirements and safety' },
  { id: 'route', es: 'Ruta y experiencia', en: 'Route and experience' },
  { id: 'preparation', es: 'Qué llevar y preparación', en: 'What to bring and preparation' },
  { id: 'planning', es: 'Planificación y elección', en: 'Planning and choosing' },
];

export function questionPath(question: BuggyQuestion, locale: QuestionLocale) {
  return locale === 'en' ? `/en/questions/${question.en.slug}` : `/preguntas/${question.es.slug}`;
}

export function questionsPath(locale: QuestionLocale) {
  return locale === 'en' ? '/en/questions' : '/preguntas';
}

export function getQuestionBySlug(slug: string, locale: QuestionLocale) {
  return buggyQuestions.find((question) => question[locale].slug === slug);
}

export function getRelatedQuestions(question: BuggyQuestion, limit = 6) {
  return buggyQuestions
    .filter((item) => item.id !== question.id && (item.category === question.category || item.destination === question.destination))
    .slice(0, limit);
}

export function categoryLabel(category: QuestionCategory, locale: QuestionLocale) {
  return questionCategories.find((item) => item.id === category)?.[locale] || category;
}
