import { siteUrl } from './buggyProducts';

export type SeoGuideLocale = 'es' | 'en';
export type SeoGuideCategory = 'destination' | 'price' | 'audience' | 'pickup' | 'planning' | 'safety';

type GuideCopy = {
  slug: string;
  title: string;
  metaTitle: string;
  description: string;
  eyebrow: string;
  intro: string;
  sections: Array<{ title: string; body: string }>;
  checklist: string[];
  faqs: Array<[string, string]>;
};

export type SeoGuide = {
  id: string;
  category: SeoGuideCategory;
  destination: 'punta-cana' | 'bayahibe' | 'general';
  productId: string;
  image: string;
  es: GuideCopy;
  en: GuideCopy;
};

export const seoGuides: SeoGuide[] = [
  {
    id: 'punta-cana-complete', category: 'destination', destination: 'punta-cana', productId: 'buggy-doble', image: '/buggy/doble.jpeg',
    es: {
      slug: 'tour-buggy-punta-cana-guia-completa', title: 'Tour en buggy en Punta Cana: guía completa para reservar', metaTitle: 'Tour en Buggy Punta Cana: Precios, Ruta y Recogida', description: 'Guía completa del tour en buggy en Punta Cana: precios por vehículo, Playa Macao, cenote, duración, recogida y cómo reservar.', eyebrow: 'Guía esencial de Punta Cana',
      intro: 'Un tour en buggy combina conducción off-road, lodo, caminos rurales y paradas en el entorno de Macao. Esta guía reúne en una sola página lo que debes decidir antes de pagar: vehículo, precio total, recogida, ruta, ropa y restricciones.',
      sections: [
        { title: 'Qué experiencia estás reservando', body: 'La salida habitual comienza con recogida coordinada, llegada al rancho, instrucciones de seguridad y asignación del vehículo. Después se recorren caminos rurales de Macao con paradas culturales y naturales. El orden puede variar por clima y operación, por lo que conviene evaluar la experiencia completa y no una sola parada.' },
        { title: 'Cómo elegir entre individual, doble y familiar', body: 'El buggy individual es para una persona que quiere conducir todo el recorrido. El doble distribuye el precio entre dos pasajeros y suele ser la opción más popular. El familiar mantiene hasta cuatro integrantes juntos. Compara capacidad y precio por vehículo, no solamente el número grande del anuncio.' },
        { title: 'Recogida, duración y confirmación', body: 'La duración publicada incluye una estimación del traslado, pero cambia según hotel, tráfico y ruta de recogida. Escribe el alojamiento exacto y espera la confirmación del punto autorizado y la hora por WhatsApp o correo antes de organizar el resto del día.' },
      ],
      checklist: ['Elegir el buggy según pasajeros', 'Escribir hotel y zona exactos', 'Usar ropa que pueda ensuciarse', 'Confirmar hora y punto antes de salir'],
      faqs: [['¿Cuánto cuesta el buggy en Punta Cana?', 'Las opciones publicadas comienzan en US$40 por vehículo individual, US$75 por doble y US$140 por familiar. La zona de recogida puede modificar el total.'], ['¿Se visita Playa Macao?', 'La operación habitual de Punta Cana incluye el entorno de Macao, cenote y playa según las condiciones del día.'], ['¿Cuánto dura?', 'Las modalidades indican aproximadamente cuatro horas con traslado; el tiempo real depende del hotel y la operación.']],
    },
    en: {
      slug: 'punta-cana-buggy-tour-complete-guide', title: 'Punta Cana buggy tour: the complete booking guide', metaTitle: 'Punta Cana Buggy Tour: Prices, Route and Pickup', description: 'Complete Punta Cana buggy tour guide covering per-vehicle prices, Macao Beach, cenote, duration, pickup and booking.', eyebrow: 'Essential Punta Cana guide',
      intro: 'A buggy tour combines off-road driving, mud, rural roads and stops around Macao. This guide puts every important decision in one place: vehicle, full price, pickup, route, clothing and restrictions.',
      sections: [
        { title: 'What experience you are booking', body: 'The usual flow starts with coordinated pickup, ranch arrival, a safety briefing and vehicle assignment. The guided route then uses Macao country roads with cultural and natural stops. Order can change with weather and operations, so evaluate the complete experience instead of choosing it for one stop alone.' },
        { title: 'Choosing single, double or family', body: 'A single buggy fits one traveler who wants to drive throughout. A double spreads the vehicle price across two travelers and is usually the most popular. A family buggy keeps up to four people together. Compare capacity and total vehicle price, not only the largest advertising number.' },
        { title: 'Pickup, duration and confirmation', body: 'Published duration includes an estimated transfer, but hotel location, traffic and pickup routing affect the real schedule. Enter the exact accommodation and wait for the authorized point and time by WhatsApp or email before arranging the rest of the day.' },
      ],
      checklist: ['Choose the buggy by traveler count', 'Enter the exact hotel and zone', 'Wear clothes that can get dirty', 'Confirm pickup time and point'],
      faqs: [['How much is a Punta Cana buggy tour?', 'Published options start at US$40 for a single vehicle, US$75 for a double and US$140 for a family buggy. Pickup zone can affect the total.'], ['Does it visit Macao Beach?', 'The usual Punta Cana operation covers the Macao area, a cenote and the beach when daily conditions allow.'], ['How long does it take?', 'Options indicate about four hours with transfer; actual timing depends on hotel and operations.']],
    },
  },
  {
    id: 'bayahibe-complete', category: 'destination', destination: 'bayahibe', productId: 'bayahibe-buggy-doble', image: '/buggy/bayahibe/buggy-lodo-bayahibe.jpg',
    es: {
      slug: 'buggy-bayahibe-la-romana-guia', title: 'Buggy en Bayahibe y La Romana: ruta, precios y recogida', metaTitle: 'Buggy Bayahibe y La Romana: Ruta, Precio y Pickup', description: 'Guía para reservar buggy en Bayahibe y La Romana con precios, modalidades, ruta rural, hoteles y recogida coordinada.', eyebrow: 'Guía local de Bayahibe',
      intro: 'Bayahibe y La Romana usan una operación distinta a Punta Cana. Esta guía ayuda a evitar la confusión más común: reservar una ruta de Macao esperando recogida en Bayahibe o asumir que todas las paradas son iguales.',
      sections: [
        { title: 'Una ruta separada de Punta Cana', body: 'La experiencia de Bayahibe se concentra en caminos rurales y entorno 4x4 de Bayahibe, La Romana y áreas operativas cercanas. No debe venderse como la misma ruta de Playa Macao. Las paradas exactas se confirman según clima, camino y operación del día.' },
        { title: 'Precios y capacidad', body: 'Las opciones publicadas comienzan con buggy individual, doble y familiar. El doble suele funcionar bien para parejas; el familiar permite mantener al grupo unido. Confirma si el precio corresponde al vehículo completo y cuántas plazas necesitas antes de pagar.' },
        { title: 'Hoteles de Bayahibe, Dominicus y La Romana', body: 'La recogida o punto de encuentro depende del alojamiento. Existen páginas específicas para hoteles de Dominicus, Bayahibe y La Romana. Escribir el nombre completo evita asignar una ruta de transporte incorrecta y permite confirmar la hora real.' },
      ],
      checklist: ['Seleccionar Bayahibe/La Romana', 'No confundir la ruta con Macao', 'Indicar hotel completo', 'Confirmar paradas operativas'],
      faqs: [['¿El buggy de Bayahibe visita Playa Macao?', 'No se debe asumir. Bayahibe tiene una operación rural distinta; confirma las paradas de esa fecha.'], ['¿Hay recogida en Dominicus?', 'Hay coordinación para hoteles populares de Dominicus y Bayahibe según la ruta operativa.'], ['¿Cuál opción sirve para dos?', 'El buggy doble está planteado para piloto y acompañante con precio por vehículo.']],
    },
    en: {
      slug: 'bayahibe-la-romana-buggy-tour-guide', title: 'Bayahibe and La Romana buggy tour: route, prices and pickup', metaTitle: 'Bayahibe and La Romana Buggy: Route, Price, Pickup', description: 'Guide to booking a Bayahibe and La Romana buggy with prices, vehicle options, rural route, hotels and coordinated pickup.', eyebrow: 'Local Bayahibe guide',
      intro: 'Bayahibe and La Romana use a different operation from Punta Cana. This guide prevents the most common mix-up: booking a Macao route while expecting Bayahibe pickup or assuming every stop is the same.',
      sections: [
        { title: 'A separate route from Punta Cana', body: 'The Bayahibe experience focuses on rural roads and 4x4 surroundings near Bayahibe, La Romana and nearby operating areas. It should not be sold as the same Macao Beach route. Exact stops are confirmed according to weather, trail and daily operations.' },
        { title: 'Prices and capacity', body: 'Published choices include single, double and family vehicles. The double is practical for couples, while the family buggy keeps a small group together. Confirm whether the displayed amount covers the complete vehicle and how many seats you need before paying.' },
        { title: 'Bayahibe, Dominicus and La Romana hotels', body: 'Pickup or meeting point depends on the accommodation. Dedicated pages cover hotels in Dominicus, Bayahibe and La Romana. Entering the full property name prevents incorrect transportation routing and lets the team confirm the real time.' },
      ],
      checklist: ['Select Bayahibe/La Romana', 'Do not confuse it with Macao', 'Enter the full hotel name', 'Confirm the operating stops'],
      faqs: [['Does the Bayahibe buggy visit Macao Beach?', 'Do not assume it does. Bayahibe uses a different rural operation; confirm the stops for your date.'], ['Is pickup available in Dominicus?', 'Coordination is available for popular Dominicus and Bayahibe hotels according to operating route.'], ['Which option fits two people?', 'The double buggy is designed for a driver and passenger with a per-vehicle price.']],
    },
  },
  {
    id: 'macao-cenote', category: 'destination', destination: 'punta-cana', productId: 'buggy-doble', image: '/buggy/ruta-2.jpeg',
    es: {
      slug: 'buggy-playa-macao-cenote-ruta', title: 'Buggy a Playa Macao y cenote: cómo es la ruta', metaTitle: 'Buggy Playa Macao y Cenote: Ruta Completa', description: 'Descubre cómo es la ruta en buggy por Macao, cenote, caminos de lodo y rancho dominicano antes de reservar.', eyebrow: 'Ruta de Macao explicada', intro: 'Macao es la intención de búsqueda más importante del tour de Punta Cana. Aquí explicamos qué ocurre entre la recogida y el regreso, qué partes dependen del clima y cómo prepararte para una experiencia real de lodo y agua.',
      sections: [{ title: 'Caminos rurales y lodo', body: 'La conducción sucede fuera del asfalto en caminos rurales guiados. La cantidad de polvo, barro y agua cambia con la lluvia. Esto no es un traslado panorámico: debes esperar movimiento, salpicaduras y ropa sucia.' }, { title: 'Rancho y parada de cenote', body: 'La ruta normalmente incorpora una parada cultural y una parada de agua. La disponibilidad, tiempo y orden los decide la operación. Protege el teléfono y lleva traje de baño debajo de la ropa si deseas entrar al agua.' }, { title: 'Playa Macao', body: 'Macao aporta el cierre costero de la experiencia cuando la operación lo permite. El tiempo de playa no equivale a un día completo; es una parada dentro de un tour guiado con horario de regreso y transporte coordinado.' }],
      checklist: ['Ropa vieja y calzado cerrado', 'Traje de baño y toalla', 'Protección para teléfono', 'Seguir siempre al guía'],
      faqs: [['¿Siempre hay lodo?', 'El terreno es off-road, pero la cantidad de lodo depende de la lluvia y las condiciones del camino.'], ['¿Puedo nadar en el cenote?', 'La parada de agua suele permitirlo cuando la operación y las condiciones lo autorizan.'], ['¿Cuánto tiempo se pasa en Macao?', 'Es una parada dentro del recorrido; el tiempo exacto depende de la operación del día.']],
    },
    en: {
      slug: 'macao-beach-cenote-buggy-route', title: 'Macao Beach and cenote buggy route: what to expect', metaTitle: 'Macao Beach and Cenote Buggy: Full Route', description: 'Learn how the Macao buggy route, cenote, mud trails and Dominican ranch work before booking.', eyebrow: 'Macao route explained', intro: 'Macao is the main route intent behind Punta Cana buggy searches. This guide explains what happens between pickup and return, which elements depend on weather and how to prepare for real mud and water.',
      sections: [{ title: 'Rural roads and mud', body: 'Driving takes place off pavement on guided country roads. Dust, mud and water levels change with rain. This is not a scenic transfer: expect movement, splashes and dirty clothing.' }, { title: 'Ranch and cenote stop', body: 'The route normally adds a cultural stop and a water stop. Operations determine availability, timing and order. Protect your phone and wear a swimsuit under your clothes if you plan to enter the water.' }, { title: 'Macao Beach', body: 'Macao provides the coastal finish when operations allow. Beach time is not a full beach day; it is one stop inside a guided tour with a return schedule and coordinated transportation.' }],
      checklist: ['Old clothes and closed shoes', 'Swimsuit and towel', 'Phone protection', 'Always follow the guide'],
      faqs: [['Is there always mud?', 'The terrain is off-road, but mud volume depends on rain and trail conditions.'], ['Can I swim in the cenote?', 'The water stop usually allows it when operations and conditions permit.'], ['How long is the Macao stop?', 'It is one stop within the route; exact timing depends on daily operations.']],
    },
  },
  {
    id: 'prices', category: 'price', destination: 'general', productId: 'buggy-doble', image: '/buggy/individual.jpeg',
    es: {
      slug: 'precios-buggy-punta-cana-comparativa', title: 'Precios de buggy en Punta Cana: comparativa por vehículo', metaTitle: 'Precios Buggy Punta Cana 2026: Individual, Doble y Familiar', description: 'Compara precios de buggy individual, doble y familiar en Punta Cana, capacidad, suplementos y costo real por persona.', eyebrow: 'Comparador de precios', intro: 'La forma correcta de comparar tours de buggy no es mirar solamente el precio inicial. Debes comprobar si la tarifa es por persona o vehículo, cuántos pasajeros caben y si la zona de recogida añade un suplemento.',
      sections: [{ title: 'Precio publicado por vehículo', body: 'Caribbean Buggy muestra opciones desde US$40 individual, US$75 doble y US$140 familiar para Punta Cana. Divide el total entre los pasajeros reales para conocer el costo efectivo por persona y comparar modalidades de manera justa.' }, { title: 'Suplementos de recogida', body: 'Bávaro, Punta Cana, Cabeza de Toro y Macao aparecen sin suplemento publicado. Cap Cana y Uvero Alto muestran un cargo de zona en el calculador. El total debe revisarse después de seleccionar ubicación y antes del pago.' }, { title: 'Qué debe incluir la comparación', body: 'Comprueba transporte, duración aproximada, vehículo, guía, casco, paradas y condiciones. Una tarifa menor puede no ser equivalente si excluye traslado o si representa solamente un depósito.' }],
      checklist: ['Confirmar si es por vehículo', 'Dividir por pasajeros', 'Seleccionar zona real', 'Revisar el total antes de pagar'],
      faqs: [['¿Cuál es el buggy más barato?', 'La opción individual de Punta Cana comienza en US$40 por vehículo para una persona.'], ['¿El doble cuesta US$75 por persona?', 'No. La tarifa publicada del doble es el total del vehículo para dos pasajeros.'], ['¿Uvero Alto tiene suplemento?', 'El calculador publica un suplemento de US$15 para Uvero Alto.']],
    },
    en: {
      slug: 'punta-cana-buggy-prices-comparison', title: 'Punta Cana buggy prices: a per-vehicle comparison', metaTitle: 'Punta Cana Buggy Prices 2026: Single, Double, Family', description: 'Compare single, double and family Punta Cana buggy prices, capacity, pickup fees and real per-person cost.', eyebrow: 'Price comparison', intro: 'The correct way to compare buggy tours is not to look only at the starting price. Check whether the rate is per person or vehicle, how many travelers fit and whether your pickup zone adds a fee.',
      sections: [{ title: 'Published price per vehicle', body: 'Caribbean Buggy lists Punta Cana choices from US$40 single, US$75 double and US$140 family. Divide the total by the actual travelers to understand the effective per-person cost and compare each option fairly.' }, { title: 'Pickup zone fees', body: 'Bavaro, Punta Cana, Cabeza de Toro and Macao show no published surcharge. Cap Cana and Uvero Alto display a zone fee in the calculator. Review the total after selecting the real location and before payment.' }, { title: 'What a fair comparison includes', body: 'Check transportation, estimated duration, vehicle, guide, helmet, stops and restrictions. A cheaper listing may not be equivalent when transportation is excluded or the displayed number is only a deposit.' }],
      checklist: ['Confirm it is per vehicle', 'Divide by travelers', 'Select the real pickup zone', 'Review total before paying'],
      faqs: [['What is the cheapest buggy?', 'The Punta Cana single option starts at US$40 per vehicle for one traveler.'], ['Is the US$75 double price per person?', 'No. The published double rate is the complete vehicle total for two travelers.'], ['Does Uvero Alto add a fee?', 'The calculator lists a US$15 Uvero Alto pickup surcharge.']],
    },
  },
  {
    id: 'couples', category: 'audience', destination: 'punta-cana', productId: 'buggy-doble', image: '/buggy/doble.jpeg',
    es: { slug: 'buggy-punta-cana-parejas', title: 'Buggy en Punta Cana para parejas: cuál reservar', metaTitle: 'Buggy Punta Cana para Parejas | Opción Doble', description: 'Guía para elegir buggy doble en Punta Cana para parejas: precio total, cambio de conductor, ropa, ruta y recogida.', eyebrow: 'Aventura para dos', intro: 'El buggy doble suele ser la combinación más clara para una pareja: un vehículo, dos plazas y posibilidad de compartir la experiencia. Antes de reservar, definan quién conducirá y si ambos cumplen los requisitos.', sections: [{ title: 'Por qué elegir el buggy doble', body: 'El precio publicado cubre el vehículo para dos viajeros, lo que permite calcular el costo sin duplicar la tarifa. Ambos permanecen juntos durante la ruta y pueden consultar si el cambio de conductor está permitido durante una parada segura.' }, { title: 'Cómo organizarse durante la ruta', body: 'El copiloto también recibe lodo, polvo y agua. Protejan teléfonos y documentos, lleven ropa vieja y acuerden quién conducirá primero. El conductor debe prestar atención a la charla de seguridad y mantener distancia.' }, { title: 'Fotos, cenote y playa', body: 'La ruta crea momentos para fotos y paradas de agua, pero las fotos comerciales no están incluidas automáticamente. Pueden usar el teléfono bajo su responsabilidad o consultar opciones disponibles durante el recorrido.' }], checklist: ['Reservar un doble para dos', 'Confirmar conductor mayor de edad', 'Proteger teléfonos', 'Llevar traje de baño'], faqs: [['¿Podemos cambiar de conductor?', 'Consúltenlo con el guía; cualquier cambio debe hacerse en una parada segura y bajo autorización.'], ['¿El precio es para los dos?', 'Sí, la tarifa publicada del doble corresponde al vehículo con dos pasajeros.'], ['¿Es una actividad romántica?', 'Es una aventura activa, con lodo y agua; funciona mejor para parejas que quieren divertirse y ensuciarse.']] },
    en: { slug: 'punta-cana-buggy-tour-for-couples', title: 'Punta Cana buggy tour for couples: which option to book', metaTitle: 'Punta Cana Buggy for Couples | Double Option', description: 'Guide to choosing a double Punta Cana buggy for couples: total price, driver changes, clothing, route and pickup.', eyebrow: 'Adventure for two', intro: 'A double buggy is usually the clearest fit for a couple: one vehicle, two seats and a shared experience. Before booking, decide who will drive and whether both travelers meet the requirements.', sections: [{ title: 'Why choose the double buggy', body: 'The listed price covers the vehicle for two travelers, so the cost does not need to be doubled. Both stay together on the route and can ask whether a driver change is allowed during a safe stop.' }, { title: 'How to organize during the route', body: 'The passenger also gets mud, dust and water. Protect phones and documents, wear old clothes and agree who drives first. The driver must follow the safety briefing and maintain distance.' }, { title: 'Photos, cenote and beach', body: 'The route creates photo moments and water stops, but commercial photos are not automatically included. Use your phone at your own risk or ask about any available options during the tour.' }], checklist: ['Book one double for two', 'Confirm an adult driver', 'Protect phones', 'Bring swimwear'], faqs: [['Can we switch drivers?', 'Ask the guide; any change must happen at a safe stop with authorization.'], ['Is the rate for both people?', 'Yes. The listed double rate covers the vehicle with two travelers.'], ['Is it a romantic activity?', 'It is an active mud-and-water adventure, best for couples who want to have fun and get dirty.']] },
  },
  {
    id: 'families', category: 'audience', destination: 'punta-cana', productId: 'buggy-familiar', image: '/buggy/familiar.jpeg',
    es: { slug: 'buggy-familiar-punta-cana-con-ninos', title: 'Buggy familiar en Punta Cana con niños: requisitos y consejos', metaTitle: 'Buggy Familiar Punta Cana con Niños | Guía', description: 'Consejos para reservar buggy familiar en Punta Cana con niños: edad mínima, plazas, seguridad, ropa, cenote y hotel.', eyebrow: 'Guía para familias', intro: 'El buggy familiar permite mantener hasta cuatro personas en el mismo vehículo, pero la decisión correcta depende de las edades, la tolerancia al movimiento y cualquier condición física. La seguridad debe confirmarse antes del pago.', sections: [{ title: 'Capacidad y edades', body: 'La opción familiar está planteada para hasta cuatro plazas. El conductor debe ser adulto y poder manejar. La edad mínima publicada para acompañantes es de tres años, aunque la operación puede rechazar la participación si una condición particular no es segura.' }, { title: 'Qué deben esperar los niños', body: 'Hay ruido, baches, polvo, lodo, calor y paradas de agua. Explícales la experiencia antes de salir y evita llevar objetos sueltos. Un adulto debe supervisar que permanezcan sentados y sigan las instrucciones.' }, { title: 'Preparación familiar', body: 'Lleven cambio de ropa, toallas, agua según autorización, protector solar biodegradable y una bolsa para lo mojado. Confirmen el punto de recogida para reducir esperas con niños.' }], checklist: ['Informar edades exactas', 'Un adulto conduce', 'Llevar cambio de ropa', 'Confirmar limitaciones físicas'], faqs: [['¿Cuál es la edad mínima?', 'La información publicada indica tres años para acompañantes, sujeto a decisión de seguridad.'], ['¿Caben cuatro adultos?', 'La modalidad indica hasta cuatro plazas; confirma distribución y comodidad antes de pagar.'], ['¿Se recomienda durante el embarazo?', 'No. La actividad off-road no se recomienda para embarazadas.']] },
    en: { slug: 'family-buggy-punta-cana-with-kids', title: 'Family buggy in Punta Cana with children: requirements and tips', metaTitle: 'Family Buggy Punta Cana with Kids | Guide', description: 'Tips for booking a family buggy in Punta Cana with children: minimum age, seats, safety, clothing, cenote and pickup.', eyebrow: 'Family guide', intro: 'A family buggy keeps up to four people in one vehicle, but the right decision depends on ages, motion tolerance and physical conditions. Safety must be confirmed before payment.', sections: [{ title: 'Capacity and ages', body: 'The family option is designed for up to four seats. The driver must be an adult able to drive. The published minimum passenger age is three, although operations can decline participation when a specific condition is not safe.' }, { title: 'What children should expect', body: 'There is noise, bouncing, dust, mud, heat and water stops. Explain the activity before departure and avoid loose items. An adult must supervise children so they remain seated and follow instructions.' }, { title: 'Family preparation', body: 'Bring spare clothing, towels, approved water, biodegradable sunscreen and a bag for wet items. Confirm the pickup point to reduce waiting time with children.' }], checklist: ['Provide exact child ages', 'An adult must drive', 'Bring spare clothes', 'Disclose physical limitations'], faqs: [['What is the minimum age?', 'Published information indicates age three for passengers, subject to the safety decision.'], ['Can four adults fit?', 'The option indicates up to four seats; confirm distribution and comfort before paying.'], ['Is it recommended during pregnancy?', 'No. Off-road activity is not recommended during pregnancy.']] },
  },
  {
    id: 'hotel-pickup', category: 'pickup', destination: 'general', productId: 'buggy-doble', image: '/buggy/ruta-3.jpeg',
    es: { slug: 'buggy-punta-cana-recogida-hotel', title: 'Buggy con recogida en hotel: zonas, horarios y puntos', metaTitle: 'Buggy Punta Cana con Recogida en Hotel | Zonas', description: 'Cómo funciona la recogida para buggy desde hoteles de Bávaro, Punta Cana, Macao, Uvero Alto, Cap Cana y Bayahibe.', eyebrow: 'Pickup explicado', intro: '“Recogida incluida” no significa que todos los vehículos entren a cualquier lobby a la misma hora. Cada hotel usa áreas autorizadas, rutas y accesos distintos. Esta guía explica cómo recibir una confirmación útil.', sections: [{ title: 'Lobby, área de tours o punto externo', body: 'El punto puede ser el lobby, el área de excursiones o un acceso cercano autorizado por seguridad. La página del hotel ofrece una referencia, pero el mensaje final es el que debes seguir.' }, { title: 'Zonas y suplementos', body: 'Las zonas principales aparecen en el calculador. Cap Cana y Uvero Alto muestran suplementos publicados por distancia y acceso. Si el alojamiento no está listado, selecciona otra zona y confirma antes de pagar.' }, { title: 'Cuándo llega la hora exacta', body: 'La hora depende de la tanda, hotel, tráfico y ruta compartida. Escribe correctamente alojamiento y teléfono. No salgas basándote solamente en un tiempo estimado de traslado.' }], checklist: ['Nombre completo del hotel', 'Zona correcta en el formulario', 'Teléfono con WhatsApp', 'Seguir la confirmación final'], faqs: [['¿Me buscan en el lobby?', 'Puede ser lobby, área de tours o punto cercano autorizado; la confirmación especifica dónde esperar.'], ['¿Regreso al mismo punto?', 'El transporte vuelve al punto coordinado salvo acuerdo diferente.'], ['¿Hay pickup desde Airbnb?', 'Puede asignarse un punto cercano según ubicación y acceso; debe confirmarse previamente.']] },
    en: { slug: 'punta-cana-buggy-hotel-pickup-guide', title: 'Buggy tour with hotel pickup: zones, times and meeting points', metaTitle: 'Punta Cana Buggy with Hotel Pickup | Zones', description: 'How buggy pickup works from Bavaro, Punta Cana, Macao, Uvero Alto, Cap Cana and Bayahibe hotels.', eyebrow: 'Pickup explained', intro: '“Pickup included” does not mean every vehicle enters every lobby at the same time. Hotels use different authorized areas, routes and access rules. This guide explains how to receive a useful confirmation.', sections: [{ title: 'Lobby, tours area or outside point', body: 'The point may be the lobby, excursions area or a nearby entrance authorized by security. A hotel page provides a reference, but the final confirmation message is the instruction to follow.' }, { title: 'Zones and surcharges', body: 'Main zones appear in the calculator. Cap Cana and Uvero Alto display published distance and access surcharges. If the accommodation is not listed, select the fallback zone and confirm before paying.' }, { title: 'When the exact time arrives', body: 'Timing depends on departure, hotel, traffic and shared routing. Enter the property and phone correctly. Do not leave based only on an estimated transfer duration.' }], checklist: ['Full hotel name', 'Correct form zone', 'Phone with WhatsApp', 'Follow final confirmation'], faqs: [['Will pickup be in the lobby?', 'It may be the lobby, tours area or an authorized nearby point; confirmation states where to wait.'], ['Do I return to the same point?', 'Transportation returns to the coordinated point unless otherwise arranged.'], ['Is Airbnb pickup available?', 'A nearby meeting point may be assigned according to location and access; confirm it in advance.']] },
  },
  {
    id: 'what-to-bring', category: 'planning', destination: 'general', productId: 'buggy-doble', image: '/buggy/ruta-2.jpeg',
    es: { slug: 'que-llevar-tour-buggy-punta-cana', title: 'Qué llevar a un tour en buggy en Punta Cana', metaTitle: 'Qué Llevar al Buggy Punta Cana: Ropa y Calzado', description: 'Lista práctica de ropa, calzado, traje de baño, toalla y protección para un tour en buggy con lodo, cenote y playa.', eyebrow: 'Lista antes de salir', intro: 'La mejor preparación cabe en una bolsa pequeña. El objetivo es protegerte del sol y el lodo sin llevar objetos que puedan perderse durante la conducción.', sections: [{ title: 'Ropa y calzado', body: 'Usa ropa vieja, cómoda y de secado rápido. El calzado cerrado ofrece mejor estabilidad que una sandalia suelta. No lleves prendas blancas o delicadas si te preocupa que se manchen.' }, { title: 'Agua, cenote y playa', body: 'Lleva traje de baño debajo de la ropa, toalla ligera y una muda seca. Usa protector solar biodegradable antes de salir y respeta las instrucciones del lugar de baño.' }, { title: 'Teléfono, dinero y documentos', body: 'Protege el teléfono en una funda impermeable y lleva solo el efectivo necesario. Deja documentos valiosos en la caja fuerte cuando sea posible. Ningún objeto debe quedar suelto dentro del buggy.' }], checklist: ['Ropa vieja', 'Calzado cerrado', 'Traje de baño y toalla', 'Funda impermeable'], faqs: [['¿Necesito gafas?', 'Las gafas ayudan con polvo y salpicaduras; confirma qué equipo entrega la operación.'], ['¿Puedo llevar mochila?', 'Mejor una bolsa pequeña bien cerrada; evita objetos sueltos.'], ['¿La ropa se mancha?', 'Es probable. El lodo y el polvo forman parte de la experiencia off-road.']] },
    en: { slug: 'what-to-wear-bring-punta-cana-buggy', title: 'What to wear and bring on a Punta Cana buggy tour', metaTitle: 'What to Bring Punta Cana Buggy: Clothes and Shoes', description: 'Practical clothing, shoes, swimwear, towel and phone protection checklist for a mud, cenote and beach buggy tour.', eyebrow: 'Pre-tour checklist', intro: 'The best preparation fits in one small bag. Protect yourself from sun and mud without carrying items that can be lost while driving.', sections: [{ title: 'Clothing and shoes', body: 'Wear old, comfortable, quick-drying clothing. Closed shoes offer better stability than loose sandals. Avoid white or delicate garments when stains would be a concern.' }, { title: 'Water, cenote and beach', body: 'Wear swimwear under your clothes, bring a light towel and pack one dry change. Apply biodegradable sunscreen before departure and follow instructions at the swimming stop.' }, { title: 'Phone, cash and documents', body: 'Protect the phone in a waterproof case and carry only necessary cash. Leave valuable documents in the hotel safe when possible. Nothing should remain loose inside the buggy.' }], checklist: ['Old clothes', 'Closed shoes', 'Swimwear and towel', 'Waterproof phone case'], faqs: [['Do I need goggles?', 'Goggles help with dust and splashes; confirm which equipment operations provide.'], ['Can I bring a backpack?', 'A small secured bag is better; avoid loose objects.'], ['Will my clothes stain?', 'Very likely. Mud and dust are part of the off-road experience.']] },
  },
  {
    id: 'safety', category: 'safety', destination: 'general', productId: 'buggy-familiar', image: '/buggy/ruta-3.jpeg',
    es: { slug: 'seguridad-requisitos-buggy-punta-cana', title: 'Seguridad y requisitos para conducir buggy en Punta Cana', metaTitle: 'Seguridad Buggy Punta Cana: Edad y Requisitos', description: 'Requisitos de edad, conducción, niños, embarazo y salud para participar con seguridad en un tour de buggy.', eyebrow: 'Seguridad antes del precio', intro: 'Una reserva correcta empieza por confirmar quién conduce y quién viaja. El terreno tiene baches, lodo y movimientos bruscos; ocultar una condición física puede convertir una actividad divertida en un riesgo.', sections: [{ title: 'Conductor y pasajeros', body: 'El conductor debe tener al menos 18 años y capacidad para manejar. Los acompañantes deben permanecer sentados y seguir al guía. Informa las edades de todos los niños antes del pago.' }, { title: 'Embarazo, espalda y condiciones médicas', body: 'La actividad no se recomienda durante el embarazo ni para personas con problemas graves de espalda. Consulta previamente si existe una cirugía reciente, movilidad reducida o una condición que pueda empeorar con los impactos.' }, { title: 'Reglas durante la conducción', body: 'Mantén distancia, no adelantes y reduce velocidad donde indique el guía. No conduzcas bajo efectos de alcohol o sustancias. La decisión operativa puede detener la participación si existe una conducta insegura.' }], checklist: ['Conductor de 18 años o más', 'Informar edades y salud', 'Usar casco indicado', 'No adelantar al guía'], faqs: [['¿Necesito licencia?', 'Los requisitos documentales deben confirmarse para la operación elegida; el conductor siempre debe ser adulto y capaz de manejar.'], ['¿Pueden ir embarazadas?', 'No se recomienda participar durante el embarazo por los impactos del terreno.'], ['¿Es seguro para niños?', 'Depende de edad y condición. La edad mínima publicada es tres años, sujeta a decisión operativa.']] },
    en: { slug: 'punta-cana-buggy-safety-age-requirements', title: 'Punta Cana buggy safety, driver age and requirements', metaTitle: 'Punta Cana Buggy Safety: Age and Requirements', description: 'Driver age, children, pregnancy, health and safe-driving requirements for joining a buggy tour.', eyebrow: 'Safety before price', intro: 'A correct booking starts by confirming who drives and who rides. The terrain includes bumps, mud and sudden movement; hiding a physical condition can turn a fun activity into a risk.', sections: [{ title: 'Driver and passengers', body: 'The driver must be at least 18 and able to operate the vehicle. Passengers must remain seated and follow the guide. Provide every child’s age before payment.' }, { title: 'Pregnancy, back and medical conditions', body: 'The activity is not recommended during pregnancy or for severe back problems. Ask in advance about recent surgery, reduced mobility or any condition that impacts can worsen.' }, { title: 'Rules while driving', body: 'Maintain distance, do not overtake and slow down where instructed. Never drive under the influence of alcohol or drugs. Operations can stop participation when behavior is unsafe.' }], checklist: ['Driver age 18 or older', 'Disclose ages and health', 'Use the required helmet', 'Never overtake the guide'], faqs: [['Do I need a license?', 'Document requirements must be confirmed for the selected operation; the driver must always be an adult able to drive.'], ['Can pregnant travelers join?', 'Participation is not recommended during pregnancy because of trail impacts.'], ['Is it safe for children?', 'It depends on age and condition. The published minimum is age three, subject to operations.']] },
  },
  {
    id: 'compare', category: 'price', destination: 'general', productId: 'buggy-doble', image: '/buggy/doble.jpeg',
    es: { slug: 'buggy-individual-doble-familiar-comparar', title: 'Buggy individual, doble o familiar: comparación completa', metaTitle: 'Buggy Individual vs Doble vs Familiar | Comparar', description: 'Compara capacidad, precio y tipo de viajero para elegir buggy individual, doble o familiar en Punta Cana y Bayahibe.', eyebrow: 'Elige el vehículo correcto', intro: 'Los tres vehículos recorren la operación asignada, pero cambian la capacidad, el precio y la experiencia dentro del buggy. Elegir bien evita pagar por otro vehículo o separar al grupo.', sections: [{ title: 'Individual: control para una persona', body: 'Conviene al viajero solo que desea conducir durante toda la ruta. No es necesariamente la mejor opción para un grupo porque cada persona necesitaría su propio vehículo.' }, { title: 'Doble: equilibrio para dos', body: 'Es la modalidad más sencilla para parejas y amigos. El precio corresponde a las dos plazas y mantiene a ambos viajeros juntos. Confirma si desean cambiar de conductor.' }, { title: 'Familiar: un grupo en el mismo vehículo', body: 'Reúne hasta cuatro plazas y suele ofrecer el menor costo efectivo por persona cuando el vehículo se completa. Revisa edades, comodidad y quién conducirá.' }], checklist: ['Contar pasajeros reales', 'Comparar precio por vehículo', 'Confirmar edades', 'No exceder las plazas'], faqs: [['¿Cuál ofrece mejor valor?', 'Depende del grupo. Un familiar completo suele bajar el costo por persona; el doble equilibra precio y comodidad para dos.'], ['¿Todos conducen?', 'No. Cada vehículo tiene un conductor a la vez; cualquier cambio requiere autorización.'], ['¿La ruta cambia por vehículo?', 'La modalidad cambia el vehículo, no necesariamente la ruta asignada al destino.']] },
    en: { slug: 'single-vs-double-vs-family-buggy', title: 'Single vs double vs family buggy: complete comparison', metaTitle: 'Single vs Double vs Family Buggy | Compare', description: 'Compare capacity, price and traveler type to choose a single, double or family buggy in Punta Cana and Bayahibe.', eyebrow: 'Choose the right vehicle', intro: 'All three vehicles follow their assigned operation, but capacity, price and the in-vehicle experience change. Choosing correctly prevents paying for another vehicle or splitting the group.', sections: [{ title: 'Single: control for one traveler', body: 'It suits a solo traveler who wants to drive throughout the route. It is not automatically best for a group because each traveler would need a separate vehicle.' }, { title: 'Double: balance for two', body: 'This is the clearest option for couples and friends. The rate covers both seats and keeps the travelers together. Ask if you plan to switch drivers.' }, { title: 'Family: one group in one vehicle', body: 'It combines up to four seats and can provide the lowest effective per-person cost when filled. Review ages, comfort and who will drive.' }], checklist: ['Count actual travelers', 'Compare per-vehicle prices', 'Confirm ages', 'Do not exceed capacity'], faqs: [['Which offers the best value?', 'It depends on the group. A full family buggy often lowers per-person cost; a double balances price and comfort for two.'], ['Does everyone drive?', 'No. Each vehicle has one driver at a time; any change requires authorization.'], ['Does the route change by vehicle?', 'The vehicle changes, but not necessarily the route assigned to the destination.']] },
  },
  {
    id: 'remote-zones', category: 'pickup', destination: 'punta-cana', productId: 'buggy-doble', image: '/buggy/ruta-1.jpeg',
    es: { slug: 'buggy-desde-uvero-alto-cap-cana', title: 'Buggy desde Uvero Alto y Cap Cana: recogida y suplementos', metaTitle: 'Buggy desde Uvero Alto y Cap Cana | Pickup', description: 'Información sobre recogida, suplementos y tiempos para reservar buggy desde hoteles de Uvero Alto y Cap Cana.', eyebrow: 'Zonas de recogida extendida', intro: 'Uvero Alto y Cap Cana están dentro del mercado de Punta Cana, pero no de la misma ruta de transporte que Bávaro. La distancia y los controles de acceso requieren una coordinación más precisa.', sections: [{ title: 'Recogida desde Uvero Alto', body: 'El calculador publica un suplemento de US$15 para Uvero Alto. Hoteles como Live Aqua, Breathless, Dreams Onyx y Excellence tienen páginas específicas con referencias de tiempo y acceso.' }, { title: 'Recogida desde Cap Cana', body: 'Cap Cana muestra un suplemento de US$10. Los complejos pueden usar controles de seguridad o puntos externos; escribe el hotel completo y espera instrucciones antes de desplazarte.' }, { title: 'Planificar el horario', body: 'Ambas zonas pueden requerir más traslado que Bávaro. No reserves otra actividad inmediatamente después. Usa la hora confirmada y considera variaciones de tráfico y recogidas compartidas.' }], checklist: ['Seleccionar la zona correcta', 'Revisar suplemento visible', 'Indicar hotel exacto', 'Dejar margen después del tour'], faqs: [['¿Uvero Alto está incluido?', 'Está disponible con un suplemento publicado de US$15.'], ['¿Cap Cana tiene pickup?', 'Sí, aparece disponible con suplemento publicado de US$10 y coordinación de acceso.'], ['¿Cuánto tarda el traslado?', 'Depende del hotel, tráfico y ruta; las páginas de hotel muestran una estimación, no una garantía.']] },
    en: { slug: 'buggy-pickup-uvero-alto-cap-cana', title: 'Buggy pickup from Uvero Alto and Cap Cana: fees and timing', metaTitle: 'Buggy from Uvero Alto and Cap Cana | Pickup', description: 'Pickup, zone fees and timing information for booking a buggy from Uvero Alto and Cap Cana hotels.', eyebrow: 'Extended pickup zones', intro: 'Uvero Alto and Cap Cana are part of the Punta Cana market but not the same transportation route as Bavaro. Distance and access controls require more precise coordination.', sections: [{ title: 'Pickup from Uvero Alto', body: 'The calculator lists a US$15 Uvero Alto surcharge. Hotels including Live Aqua, Breathless, Dreams Onyx and Excellence have dedicated pages with timing and access references.' }, { title: 'Pickup from Cap Cana', body: 'Cap Cana shows a US$10 surcharge. Resorts may use security controls or outside points; enter the full hotel and wait for instructions before moving.' }, { title: 'Planning the schedule', body: 'Both zones can require more transfer time than Bavaro. Do not place another activity immediately after the tour. Use the confirmed time and allow for traffic and shared pickups.' }], checklist: ['Select the correct zone', 'Review the visible fee', 'Enter the exact hotel', 'Leave time after the tour'], faqs: [['Is Uvero Alto included?', 'It is available with a published US$15 zone surcharge.'], ['Does Cap Cana have pickup?', 'Yes. It is listed with a US$10 surcharge and access coordination.'], ['How long is the transfer?', 'It depends on hotel, traffic and routing; hotel pages provide an estimate, not a guarantee.']] },
  },
  {
    id: 'last-minute', category: 'planning', destination: 'general', productId: 'buggy-doble', image: '/buggy/ruta-3.jpeg',
    es: { slug: 'reservar-buggy-punta-cana-ultima-hora', title: 'Reservar buggy en Punta Cana de última hora o el mismo día', metaTitle: 'Buggy Punta Cana Hoy | Reserva de Última Hora', description: 'Cómo comprobar disponibilidad de buggy hoy o mañana en Punta Cana: datos necesarios, pickup, pago y confirmación.', eyebrow: 'Reserva rápida sin errores', intro: 'Una reserva para hoy no se confirma solo porque el formulario acepte la fecha. El equipo debe validar vehículo, tanda y ruta de recogida. Enviar la información completa desde el primer mensaje acelera la respuesta.', sections: [{ title: 'Datos que debes tener listos', body: 'Envía fecha, cantidad de personas, tipo de buggy, hotel exacto, zona y un teléfono con WhatsApp. Si hay niños, añade sus edades. Evita mensajes separados que obliguen al equipo a solicitar cada dato.' }, { title: 'Disponibilidad y pago', body: 'La plaza depende de vehículos, conductores, transporte y operación del día. No te desplaces al punto hasta recibir confirmación. Revisa el total y conserva el comprobante de pago o reserva.' }, { title: 'Alternativas cuando una tanda se llena', body: 'Considera otra salida, otro vehículo con capacidad suficiente o el día siguiente. Cambiar de individual a doble o familiar solo tiene sentido si respeta las plazas y el presupuesto del grupo.' }], checklist: ['Fecha y cantidad de personas', 'Hotel y zona exactos', 'Vehículo preferido', 'Esperar confirmación real'], faqs: [['¿Puedo reservar para hoy?', 'Puedes solicitarlo, pero la disponibilidad del mismo día requiere confirmación operativa.'], ['¿El formulario garantiza la plaza?', 'No por sí solo; la confirmación valida vehículo, pickup y tanda.'], ['¿Es mejor escribir por WhatsApp?', 'Para última hora, WhatsApp permite enviar todos los datos y recibir una respuesta operativa rápida.']] },
    en: { slug: 'last-minute-punta-cana-buggy-today', title: 'Last-minute or same-day Punta Cana buggy booking', metaTitle: 'Punta Cana Buggy Today | Last-Minute Booking', description: 'How to check buggy availability today or tomorrow in Punta Cana: required details, pickup, payment and confirmation.', eyebrow: 'Fast booking without mistakes', intro: 'A same-day booking is not confirmed simply because a form accepts the date. The team must validate vehicle, departure and pickup route. Sending complete information in the first message speeds up the response.', sections: [{ title: 'Details to have ready', body: 'Send date, traveler count, preferred buggy, exact hotel, zone and a WhatsApp phone. Include children’s ages. Avoid separate messages that force the team to request each missing detail.' }, { title: 'Availability and payment', body: 'Space depends on vehicles, drivers, transportation and daily operations. Do not travel to the meeting point until confirmed. Review the total and keep the payment or reservation receipt.' }, { title: 'Alternatives when a departure fills', body: 'Consider another departure, a different vehicle with enough capacity or the next day. Switching from single to double or family only works when it respects group seats and budget.' }], checklist: ['Date and traveler count', 'Exact hotel and zone', 'Preferred vehicle', 'Wait for real confirmation'], faqs: [['Can I book for today?', 'You can request it, but same-day availability requires operating confirmation.'], ['Does the form guarantee space?', 'Not by itself; confirmation validates the vehicle, pickup and departure.'], ['Should I use WhatsApp?', 'For last-minute requests, WhatsApp lets you send all details and receive a faster operating answer.']] },
  },
];

export const guideCategoryLabels: Record<SeoGuideLocale, Record<SeoGuideCategory, string>> = {
  es: { destination: 'Destinos y rutas', price: 'Precios y vehículos', audience: 'Tipo de viajero', pickup: 'Recogida en hotel', planning: 'Planificación', safety: 'Seguridad' },
  en: { destination: 'Destinations and routes', price: 'Prices and vehicles', audience: 'Traveler type', pickup: 'Hotel pickup', planning: 'Planning', safety: 'Safety' },
};

export function guidePath(guide: SeoGuide, locale: SeoGuideLocale) {
  return locale === 'en' ? `/en/guides/${guide.en.slug}` : `/guias/${guide.es.slug}`;
}

export function guidesPath(locale: SeoGuideLocale) {
  return locale === 'en' ? '/en/guides' : '/guias';
}

export function guideCanonical(guide: SeoGuide, locale: SeoGuideLocale) {
  return `${siteUrl}${guidePath(guide, locale)}`;
}

export function getSeoGuideBySlug(slug: string, locale: SeoGuideLocale) {
  return seoGuides.find((guide) => guide[locale].slug === slug);
}

export function getRelatedSeoGuides(current: SeoGuide, limit = 4) {
  return seoGuides
    .filter((guide) => guide.id !== current.id)
    .sort((a, b) => {
      const score = (guide: SeoGuide) => Number(guide.destination === current.destination) * 2 + Number(guide.category === current.category);
      return score(b) - score(a);
    })
    .slice(0, limit);
}

export function getGuideForContext(category: string, destination: string) {
  const exact = seoGuides.find((guide) => guide.category === category && (guide.destination === destination || guide.destination === 'general'));
  return exact ?? seoGuides.find((guide) => guide.destination === destination) ?? seoGuides[0];
}
